version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: flashsale-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flashsale_db
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: flashsale-redis
    ports:
      - "6379:6379"